# Get comments by post ID
GET http://localhost:3334/blog/posts/693c1d21-a2ec-45b0-9b3c-633dc161a735/comments HTTP/1.1
Content-Type: application/json

###

# Create a new comment
POST http://localhost:3334/blog/posts/2243f6bc-b406-4155-8096-387190929516/comments HTTP/1.1
Content-Type: application/json

{
  "authorId": "658170cbb954e9f5b905ccf4",
  "content": "Something wrong.."
}

###

# Get comment by ID
GET http://localhost:3334/blog/posts/6d308040-96a2-4162-bea6-2338e9976540/comments/c08fc578-4578-4958-98e3-b66f8ae64e57 HTTP/1.1

###

# Update comment by ID
PUT http://localhost:3334/blog/posts/6d308040-96a2-4162-bea6-2338e9976540/comments/2d0387dd-864e-4f10-8e6b-ca5f9bd10d1c HTTP/1.1
Content-Type: application/json

{
  "content": "Content 1 updated"
}

###

# Delete comment by ID
DELETE http://localhost:3334/blog/posts/6d308040-96a2-4162-bea6-2338e9976540/comments/2d0387dd-864e-4f10-8e6b-ca5f9bd10d1c HTTP/1.1

###
