# Create a new user
POST http://localhost:3333/account/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@found.local",
  "firstName": "Keks",
  "lastName": "Smith",
  "password": "123SwEf6!sdf@w_1",
  "avatarSrc": "/avatar.png"
}

###

# Get user by ID
GET http://localhost:3333/account/auth/67d9e507897b919848c35d95 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Q5ZTUwNzg5N2I5MTk4NDhjMzVkOTUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3ROYW1lIjoiU21pdGgiLCJmaXJzdE5hbWUiOiJLZWtzIiwiaWF0IjoxNzQzMzY3ODUzLCJleHAiOjE3NDMzNjgxNTN9.BMkmoX8kVpCiJ_Fk--mUxagEhYwNSzz2VH0hb1ci18s

###

# Login user by email and password
POST http://localhost:3333/account/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
