# Create a new user
POST http://localhost:3333/account/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "345@found.local",
  "firstName": "Keks",
  "lastName": "Smith",
  "password": "123SwEf6!sdf@w_1",
  "avatarSrc": "/avatar.png"
}

###

# Get user by ID
GET http://localhost:3333/account/auth/67f85d233346ca3e3f5f7714 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Y4NWQyMzMzNDZjYTNlM2Y1Zjc3MTQiLCJlbWFpbCI6Indhc2RAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImxhc3ROYW1lIjoiZWFzZCIsImZpcnN0TmFtZSI6ImVkIiwiaWF0IjoxNzQ1NTMxNjA0LCJleHAiOjE3NDU1Mzg4MDR9.jN6mwvnsgMKVJiqXfD-xo3EvMiQ2UGzPLPtijz_3ONo
###

# Login user by email and password
POST http://localhost:3333/account/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "wasd@mail.com",
  "password": "ed323cw!4cds!D"
}

###

# Refresh token
POST http://localhost:3333/account/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Y4NWQyMzMzNDZjYTNlM2Y1Zjc3MTQiLCJlbWFpbCI6Indhc2RAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImxhc3ROYW1lIjoiZWFzZCIsImZpcnN0TmFtZSI6ImVkIiwidG9rZW5JZCI6ImIxODJkMWE1LWE4NDYtNDQ1OS1iNTZjLWU4YjQzYjMyOWFiZSIsImlhdCI6MTc0NDQ5OTg0MSwiZXhwIjoxNzQ3MDkxODQxfQ.X1-TgeteCsWTEorot3kOH6v0niQRK979xvOB58qJ5zM

###

# Check token
POST http://localhost:3333/account/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Y4NWQyMzMzNDZjYTNlM2Y1Zjc3MTQiLCJlbWFpbCI6Indhc2RAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImxhc3ROYW1lIjoiZWFzZCIsImZpcnN0TmFtZSI6ImVkIiwiaWF0IjoxNzQ1NTI4OTQ5LCJleHAiOjE3NDU1MzYxNDl9.BZh4RMTBuzlMmPjk31ZinuwrBx-cAddX79UDjZ6ugFw

###

# Logout user
POST http://localhost:3333/account/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Y4NWQyMzMzNDZjYTNlM2Y1Zjc3MTQiLCJlbWFpbCI6Indhc2RAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImxhc3ROYW1lIjoiZWFzZCIsImZpcnN0TmFtZSI6ImVkIiwiaWF0IjoxNzQ1NTI4OTQ5LCJleHAiOjE3NDU1MzYxNDl9.BZh4RMTBuzlMmPjk31ZinuwrBx-cAddX79UDjZ6ugFw

###
