
# Create a new post
POST http://localhost:3334/blog/posts HTTP/1.1
Content-Type: application/json

{
  "authorId": "67d9e507897b919848c35d95",
  "status": "published",
  "tags": ["tag1", "tag2"],
  "data": {
    "kind": "text",
    "name": "Post 1",
    "content": "Content 1"
  }
}

###

# Get post by ID
GET http://localhost:3334/blog/posts/67d9f3583f0b00a7e47af919 HTTP/1.1

###

# Update post by ID
PUT http://localhost:3334/blog/posts/67d9fe0a3c8d60de3e88fb9a HTTP/1.1
Content-Type: application/json

{
  "data": {
    "name": "Post 1 updated",
    "content": "Content 1 updated"
  }
}

###

# Delete post by ID
DELETE http://localhost:3334/blog/posts/67d9f3583f0b00a7e47af919 HTTP/1.1

###
